version: '3.8'

services:
  chatbot:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./chroma_db:/app/chroma_db
      - ./.env:/app/.env
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    restart: unless-stopped 